Traceback (most recent call last):
  File "E:\MainHomePage\.M_HomePage\Lib\site-packages\jupyter_cache\executors\utils.py", line 58, in single_nb_execution
    executenb(
  File "E:\MainHomePage\.M_HomePage\Lib\site-packages\nbclient\client.py", line 1314, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\MainHomePage\.M_HomePage\Lib\site-packages\jupyter_core\utils\__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dr\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "E:\MainHomePage\.M_HomePage\Lib\site-packages\nbclient\client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "E:\MainHomePage\.M_HomePage\Lib\site-packages\nbclient\client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "E:\MainHomePage\.M_HomePage\Lib\site-packages\nbclient\client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import numpy as np
import matplotlib.pyplot as plt

import PySpice.Logging.Logging as Logging
logger = Logging.setup_logging()
from PySpice.Spice.Netlist import Circuit
from PySpice.Unit import *

# Define sweep parameters
Vinput_start = -120
Vinput_stop = 20
Vinput_step = 0.001

# Define the circuit
circuit = Circuit('First Example Define diode')

# Add a diode with specific parameters
circuit.D('1', '2', circuit.gnd, model='Diode')

circuit.model('Diode', 'D', IS=4.352E-9, BV = 110, GMIN = 1E-12,
               N=1.906, IBV = 0.0001, RS = 0.6458,
                 CJO = 7.048E-13, VJ = 0.869, M = 0.03, FC = 0.5 , TT = 3.48E-9 
                   )

circuit.V('input', '1', circuit.gnd, 5)
circuit.V('meas', '1', '2', 0)
# Create a simulator
simulator = circuit.simulator(temperature=25, nominal_temperature=25)

# Perform a DC sweep analysis
analysis = simulator.dc(Vinput=slice(Vinput_start, Vinput_stop, Vinput_step))

waveform = analysis['2']
sweep_values1=analysis['v-sweep']
InputCurrentMeasurement=analysis['vmeas']
# Assuming waveform.data provides the voltage values for node '3'
voltage_values = np.array(waveform)

plt.xscale('symlog', linthresh=1)

plt.plot(voltage_values,InputCurrentMeasurement)
plt.xlabel('Vinput (V)')
plt.ylabel('Input current (A)')
plt.title('DC Sweep Analysis for input Node current')
plt.grid(True)
plt.show()

------------------


[1;31m---------------------------------------------------------------------------[0m
[1;31mModuleNotFoundError[0m                       Traceback (most recent call last)
Cell [1;32mIn[2], line 4[0m
[0;32m      1[0m [38;5;28;01mimport[39;00m [38;5;21;01mnumpy[39;00m [38;5;28;01mas[39;00m [38;5;21;01mnp[39;00m
[0;32m      2[0m [38;5;28;01mimport[39;00m [38;5;21;01mmatplotlib[39;00m[38;5;21;01m.[39;00m[38;5;21;01mpyplot[39;00m [38;5;28;01mas[39;00m [38;5;21;01mplt[39;00m
[1;32m----> 4[0m [38;5;28;01mimport[39;00m [38;5;21;01mPySpice[39;00m[38;5;21;01m.[39;00m[38;5;21;01mLogging[39;00m[38;5;21;01m.[39;00m[38;5;21;01mLogging[39;00m [38;5;28;01mas[39;00m [38;5;21;01mLogging[39;00m
[0;32m      5[0m logger [38;5;241m=[39m Logging[38;5;241m.[39msetup_logging()
[0;32m      6[0m [38;5;28;01mfrom[39;00m [38;5;21;01mPySpice[39;00m[38;5;21;01m.[39;00m[38;5;21;01mSpice[39;00m[38;5;21;01m.[39;00m[38;5;21;01mNetlist[39;00m [38;5;28;01mimport[39;00m Circuit

[1;31mModuleNotFoundError[0m: No module named 'PySpice'

