Traceback (most recent call last):
  File "E:\MainHomePage\.M_HomePage\Lib\site-packages\jupyter_cache\executors\utils.py", line 58, in single_nb_execution
    executenb(
  File "E:\MainHomePage\.M_HomePage\Lib\site-packages\nbclient\client.py", line 1314, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\MainHomePage\.M_HomePage\Lib\site-packages\jupyter_core\utils\__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dr\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "E:\MainHomePage\.M_HomePage\Lib\site-packages\nbclient\client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "E:\MainHomePage\.M_HomePage\Lib\site-packages\nbclient\client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "E:\MainHomePage\.M_HomePage\Lib\site-packages\nbclient\client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import numpy as np

import PySpice.Logging.Logging as Logging
logger = Logging.setup_logging()
from PySpice.Spice.Netlist import Circuit


circuit = Circuit('First Example Define diode')

## Example 1
circuit.D('1','3', circuit.gnd, model='Diode')
circuit.model('Diode', 'D', IS=0.0000000001, rs=0.0341512, nd=2, eg=1.05743, xti=5, bv=1000, ibv=5e-08, cjo=10, vj=0.7, m=0.5, fc=0.5, tt=1e-07, kf=0, af=1)

------------------


[1;31m---------------------------------------------------------------------------[0m
[1;31mModuleNotFoundError[0m                       Traceback (most recent call last)
Cell [1;32mIn[1], line 3[0m
[0;32m      1[0m [38;5;28;01mimport[39;00m [38;5;21;01mnumpy[39;00m [38;5;28;01mas[39;00m [38;5;21;01mnp[39;00m
[1;32m----> 3[0m [38;5;28;01mimport[39;00m [38;5;21;01mPySpice[39;00m[38;5;21;01m.[39;00m[38;5;21;01mLogging[39;00m[38;5;21;01m.[39;00m[38;5;21;01mLogging[39;00m [38;5;28;01mas[39;00m [38;5;21;01mLogging[39;00m
[0;32m      4[0m logger [38;5;241m=[39m Logging[38;5;241m.[39msetup_logging()
[0;32m      5[0m [38;5;28;01mfrom[39;00m [38;5;21;01mPySpice[39;00m[38;5;21;01m.[39;00m[38;5;21;01mSpice[39;00m[38;5;21;01m.[39;00m[38;5;21;01mNetlist[39;00m [38;5;28;01mimport[39;00m Circuit

[1;31mModuleNotFoundError[0m: No module named 'PySpice'

